name: Go Security Scan

on:
  push:
    branches: [ main, v2_test ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 1 * * 1' # Weekly on Mondays

jobs:
  gosec:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Source
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          cache: true


      - name: Run Gosec Security Scanner
        uses: securego/gosec@v2.26.1
        with:
          args: ./...
